### ISSUE TITLE
Old Json Lib used in example

### ISSUE THREAD

**Issue by FrankWalde** [PLCnext/IIOT_Library#2]
The examples contains an older Library version which causes some errors and warnings in PLCnext Engineer.
<img width="430" alt="Json_Lib_Example_old_Version" src="https://user-images.githubusercontent.com/58546806/112464244-89e99f00-8d63-11eb-9225-153a43dd0095.png">
The most current version from the PLCnext Store does not show those error messages

**Comment by martinboers** [comment]
I am afraid that I cannot reproduce this. The archived PLCnext Engineer project in this repository does not appear to contain either the JSON library, or the MQTT Client library. I suspect that an old version of the JSON library was on the PC when this project was opened, which could have caused these errors.

Please check this again and let us know.

**Comment by PxCxJSP** [comment]
Hi I have successfully run the example with a AXC F 3152 FW 2021.0.3. By using the same rutine, the same could not be achieved with two other AXC F 3152 FW 2021.0.3. These errors in the online log window of PLCnext Engineer will be present upon project download, hotkey F5:
![bilde](https://user-images.githubusercontent.com/45592378/112654982-3dc85880-8e50-11eb-88c1-950df482b94b.png)

In the referenced path the SharedLibraies folder containing the *.so files is not present. By copying the folder manualy from the working AXC F 3152(picture below), the same errors will occur.
![bilde](https://user-images.githubusercontent.com/45592378/112656964-399d3a80-8e52-11eb-8db3-b47971bbd4a2.png)

**Comment by FrankWalde** [comment]
Hey,

I've had oviously an older version presintalled.
Thanks for your help!
