### ISSUE TITLE
Native library not found

### ISSUE THREAD

**Issue by PxCxJSP** [PLCnext/IIOT_Library#3]
Hi I have successfully run the example project for PLCnext Engineer(2021.0.2) with a AXC F 3152 FW 2021.0.3. By using the same rutine, the same could not be achieved with two other AXC F 3152 FW 2021.0.3. These errors in the online log window of PLCnext Engineer will be present upon project download, hotkey F5:
![bilde](https://user-images.githubusercontent.com/45592378/112831810-bfa8c380-9094-11eb-9dc8-5d55b53d6133.png)

In the referenced path the SharedLibraies folder containing the *.so files is not present. By copying the folder manualy from the working AXC F 3152(picture below), the same errors will occur.
![bilde](https://user-images.githubusercontent.com/45592378/112831777-b586c500-9094-11eb-9f4e-580076e2a367.png)

**Comment by martinboers** [comment]
I cannot reproduce this problem on AXC F 3152 FW 2021.0.3, using PLCnext Engineer 2021.0.2 and the JSON_utility_library.

It's not clear if you are using the JSON_utility_library from the PLCnext Store, or the IIOT_Library, or both.

Which library(s) are installed in the PLCnext Engineer project?

These are the libraries that I am using, in a project that works OK:

![image](https://user-images.githubusercontent.com/13133969/113009681-7467e100-9178-11eb-9eaa-f7fa652e9392.png)

... and I am using the corresponding PLC version in the project:

![image](https://user-images.githubusercontent.com/13133969/113009979-c01a8a80-9178-11eb-9460-5847a04cd510.png)

Can you confirm whether these details match your project, or not?

**Comment by PxCxJSP** [comment]
Hi,

The libraies used in the project was downloaded from PLCnext Store:
JSON_utility_library_1
MQTT_Client_Library_2

The libraies was placed in this path:
![bilde](https://user-images.githubusercontent.com/45592378/114527029-cf550a00-9c47-11eb-927a-b19a250f169a.png)

After adding the library to this path(picture below) and changing the refrence in PLCnext Engineer by right clikk the library icon and select replace, the errors dissapeared.
![bilde](https://user-images.githubusercontent.com/45592378/114527130-e72c8e00-9c47-11eb-8d46-3f1df64ca796.png)

**Comment by martinboers** [comment]
What you've described is the installation process that is suggested in the documentation.

So, by following the suggested installation process, the problem is solved? Is that correct?

**Comment by PxCxJSP** [comment]
At the install of the librarys a different path than default was selected. If the default path where to be used it seems that I would not get the erros described above. So you are correct, if the documentation where to be followed wihtout the path change I would not get the error. Thanks
