### ISSUE TITLE
TLS  encrypted password

### ISSUE THREAD

**Issue by JarrenGoes** [PLCnext/IIoT_Library#8]
Hy i'm using this library for a project where the password is TLS encrypted. 
On first sight I can't see any info about this in de manual. 
Does anyone know how to configure the client to connect with the broker ?

Thanks in advance

Jarren

**Comment by martinboers** [comment]
There is some information on the TLS parameters in the PDF document that comes with the library, in the section MQTT_UDT_SSL_OPTIONS.

The TLS (SSL) option on the connect method are passed straight through to the corresponding parameters on the Paho MQTT Client object.

One suggestion is to use a Windows-based MQTT client like MQTT.fx to test the connection to the broker. The screen shot below shows the SSL/TLS configuration section on the free version of MQTT.fx:

![image](https://user-images.githubusercontent.com/13133969/150550070-6b4a5c1c-0226-4e6e-8fda-4e0b4aa6e256.png)

Once you get the connection working with something like MQTT.fx, then you know that the broker and the certificates are all working correctly. The same certificates and settings should then work in the PLC.

**Comment by JarrenGoes** [comment]
I can connect with the server MQTT explorrer and node red on the plc so i'm not sure if this is the right way?
(sServerPassword is the string with the password in)
![image](https://user-images.githubusercontent.com/65536803/150747118-2c384ef3-4a3f-4c0f-b6b2-c1e54e7ed2ac.png)

**Comment by martinboers** [comment]
If you're using SSL options then you need at least one certificate file, like shown in the MQTT.fx screen shot above.
Exactly what MQTT parameters worked with MQTT Explorer and Node Red? Can you show a screen shot, or list the parameters and their values in MQTT Explorer or Node Red? (without giving away any private information).

**Comment by JarrenGoes** [comment]
This is how the MQTT Explorer is configured (encryption tls) is marked on:
![image](https://user-images.githubusercontent.com/65536803/150966237-f7cef312-8d2d-45e5-b4bf-bfac521bba22.png)
And this is how the node red mqtt client is configured:
![image](https://user-images.githubusercontent.com/65536803/150966566-a89a6109-0238-4091-8349-c13d6d026ea8.png)
All the certificates files are blank in node red
![image](https://user-images.githubusercontent.com/65536803/150966530-09d9f95d-27ca-4136-a4f5-790b929dabff.png)

**Comment by martinboers** [comment]
I might be missing somethng, but I find it difficult to understand how TLS can be used without certificates.
I am thinking that these connections are not using TLS, even though the "TLS" option is selected, because there is no certificate information.
At the very least, a TLS connection needs the server certificate (as far as I know).
Are you able to confirm with the server administrator that the server is set up to use **TLS** on port 1884? MQTT servers typically listen on port 1883 (for TCP connections) and/or port 8883 (for TLS connections).
You could also try the same connection from MQTT Explorer/Node Red using exactly the same parameters, but without the TLS option selected. Does that also work?

**Comment by martinboers** [comment]
Slight correction (or addition) to the above:
The [Mosquitto MQTT test server](https://test.mosquitto.org/) also listens on port 1884, for unencrypted but authenticated connections. This seems to fit with the case you describe - the connection is authenticated (with user name and password), but I suspect it is unencrypted (i.e. not using TLS). The server administrator should be able to confirm if this is the case.

**Comment by JarrenGoes** [comment]
If the tls option in node red or mqtt explorer is not on then it the don't connect with the server.
![image](https://user-images.githubusercontent.com/65536803/150992121-c70b4aa0-5392-438d-bc35-b323382c74ec.png)
But it kind works now, when the certificates are uploaded to the plc it works. 
The problem is that the server administator made it so that ssl is also possible .
So we are not sure if the plc is connected on tls or ssl. I will post the answer in the near futher.

many thanks for your time Martin

**Comment by martinboers** [comment]
OK, glad to hear that it's working.
The URL on the PLC will start with either `tcp://` or `ssl://`
It will only be connected via SSL (aka TLS) when the URL starts with `ssl://`
